# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: lewisferreira/rotten-potatoes:2.0
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb-service
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongoblob
          - name: MONGODB_PASSWORD
            value: blobpwd
---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort
